---

- name: create logging directory {{ redis_general.logfile | dirname }}
  file:
    path: "{{ redis_general.logfile | dirname }}"
    state: directory
    group: redis
    mode: 0755
  tags:
    - redis
    - redis_configure

- name: create splitted redis configuration
  template:
    src: redis.d/{{ item }}.j2
    dest: /etc/redis.d/{{ item }}
    mode: 0644
    group: redis
  loop:
    - active_defragmentation.conf
    - advanced_config.conf
    - append_only.conf
    - clients.conf
    - cluster_docker_nat.conf
    - event_notification.conf
    - general.conf
    - latency_monitor.conf
    - lazy_freeing.conf
    - lua_scripting.conf
    - memory_management.conf
    - network.conf
    - redis_cluster.conf
    - replication.conf
    - security.conf
    - slow_log.conf
    - snapshotting.conf
  notify:
    - restart redis
  tags:
    - redis
    - redis_configure

- name: write redis configuration
  template:
    src: redis.conf.j2
    dest: "{{ redis_config_file }}"
    mode: 0644
    group: redis
    backup: true
  notify:
    - restart redis
  tags:
    - redis
    - redis_configure


- name: sentinel support
  when:
    - redis_sentinel.enabled is defined
    - redis_sentinel.enabled
    - redis_sentinel.master is defined
    - redis_sentinel.master | string | length > 0
    - redis_sentinel.master | ipaddr('address')
  tags:
    - redis
    - redis_configure
    - redis_sentinel
  block:
    - name: fix config directory rights
      file:
        path: "{{ redis_sentinel_config_file | dirname }}"
        group: redis
        mode: 0775

    - name: create redis-sentinel configuration
      template:
        src: sentinel.conf.j2
        dest: "{{ redis_sentinel_config_file }}"
        mode: 0664
        group: redis
        backup: true
      notify:
        - restart redis-sentinel

...
