---

role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "redis_cluster_primary"
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - redis
    docker_networks:
      - name: redis_cluster
        ipam_config:
          - subnet: "10.12.0.0/24"
            gateway: "10.12.0.254"
    networks:
      - name: redis_cluster
        ipv4_address: "10.12.0.1"

  - name: "redis_cluster_replica_1"
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - redis
      - redis_replica
    networks:
      - name: redis_cluster
        ipv4_address: "10.12.0.2"

  - name: "redis_cluster_replica_2"
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - redis
      - redis_replica
    networks:
      - name: redis_cluster
        ipv4_address: "10.12.0.3"

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      callback_result_format: yaml
      callbacks_enabled: profile_tasks
      gathering: smart
      fact_caching_timeout: 320

scenario:
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: testinfra
