---

- name: restart redis
  ansible.builtin.service:
    name: "{{ redis_daemon }}"
    state: restarted

- name: restart redis-sentinel
  ansible.builtin.service:
    name: "{{ redis_sentinel_daemon }}"
    state: restarted
  when:
    - redis_sentinel.enabled is defined
    - redis_sentinel.enabled

...
